version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vetterati_ats
      POSTGRES_USER: ats_user
      POSTGRES_PASSWORD: ats_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ats-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ats-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ats-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ats_user
      RABBITMQ_DEFAULT_PASS: ats_password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ats-network

  # Job Service (Python)
  job-service:
    build:
      context: ./src/services/job-service
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://ats_user:ats_password@postgres:5432/vetterati_ats
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - ats-network

  # Candidate Service (Python)
  candidate-service:
    build:
      context: ./src/services/candidate-service
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://ats_user:ats_password@postgres:5432/vetterati_ats
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - ats-network

  # Notification Service (Python)
  notification-service:
    build:
      context: ./src/services/notification-service
      dockerfile: Dockerfile
    ports:
      - "8006:8000"
    environment:
      - DATABASE_URL=postgresql://ats_user:ats_password@postgres:5432/vetterati_ats
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://ats_user:ats_password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - ats-network

volumes:
  postgres_data:
  elasticsearch_data:

networks:
  ats-network:
    driver: bridge
